# Generated by Django 4.1.1 on 2023-08-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_teammember_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='crm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
