# Generated by Django 4.1.1 on 2023-05-12 11:19

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='OffPlansProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('description', django_quill.fields.QuillField(verbose_name='Description')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Price')),
                ('developer', models.CharField(max_length=255, verbose_name='Developer')),
                ('project_company_logo', models.ImageField(upload_to='project_company_logos/', verbose_name='Project Company Logo')),
                ('handover_date', models.DateField(verbose_name='Handover Date')),
                ('broucher', models.FileField(blank=True, null=True, upload_to='brochures/', verbose_name='Brochure')),
                ('youtube_video_link', models.URLField(verbose_name='YouTube Video Link')),
                ('amenities', models.ManyToManyField(to='properties.amenity', verbose_name='Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='properties.offplansproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], max_length=255, verbose_name='Type')),
                ('media_file', models.FileField(upload_to='property_gallery/', verbose_name='Media File')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.offplansproperty', verbose_name='Property')),
            ],
        ),
    ]
