# Generated by Django 4.1.1 on 2023-05-24 10:58

from django.db import migrations, models
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('description', django_quill.fields.QuillField(verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='offplansproperty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
