# Generated by Django 4.1.1 on 2023-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_news_offplansproperty_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default-news.jpeg', null=True, upload_to='thumbnails'),
        ),
    ]
