# Generated by Django 4.1.1 on 2023-06-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_contactform_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='thumbnails/open-house-default.jpg', null=True, upload_to='open-houses-thumbnails')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbnails/default-news.jpeg', null=True, upload_to='news-thumbnails'),
        ),
        migrations.AlterField(
            model_name='offplansproperty',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='off-plan-thumbnails'),
        ),
    ]
