# Generated by Django 4.1.1 on 2023-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_openhouse_alter_news_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='thumbnails/open-house-default.jpg', null=True, upload_to='popular-areas-thumbnails')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
