# Generated by Django 4.1.1 on 2023-06-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_offplansproperty_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('advance', 'Advance'), ('installment', 'Installment')], max_length=25)),
                ('percent', models.IntegerField(verbose_name='Percent %')),
            ],
        ),
        migrations.AddField(
            model_name='offplansproperty',
            name='payment_plan',
            field=models.ManyToManyField(to='properties.paymentplan', verbose_name='Payment Plan'),
        ),
    ]
