# Generated by Django 4.1.1 on 2023-06-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_offplansproperty_payment_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('advance', 'Advance'), ('installment', 'Installment')], max_length=25)),
                ('percent', models.IntegerField(verbose_name='Percent %')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='properties.offplansproperty', verbose_name='Property')),
            ],
        ),
    ]
