# Generated by Django 4.1.1 on 2023-07-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_booking_alter_contactform_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='thumbnails/home-page-site-default.jpg', null=True, upload_to='home-page-sites')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
