# Generated by Django 4.1.1 on 2023-08-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_offplansproperty_date_offplansproperty_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhouse',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='installment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
